//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemsWeb.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ItemsWCF")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categories", Namespace="http://schemas.datacontract.org/2004/07/ItemsWCF")]
    [System.SerializableAttribute()]
    public partial class Categories : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Category_imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Category_nameArField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Category_nameEnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category_image {
            get {
                return this.Category_imageField;
            }
            set {
                if ((object.ReferenceEquals(this.Category_imageField, value) != true)) {
                    this.Category_imageField = value;
                    this.RaisePropertyChanged("Category_image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category_nameAr {
            get {
                return this.Category_nameArField;
            }
            set {
                if ((object.ReferenceEquals(this.Category_nameArField, value) != true)) {
                    this.Category_nameArField = value;
                    this.RaisePropertyChanged("Category_nameAr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category_nameEn {
            get {
                return this.Category_nameEnField;
            }
            set {
                if ((object.ReferenceEquals(this.Category_nameEnField, value) != true)) {
                    this.Category_nameEnField = value;
                    this.RaisePropertyChanged("Category_nameEn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Items", Namespace="http://schemas.datacontract.org/2004/07/ItemsWCF")]
    [System.SerializableAttribute()]
    public partial class Items : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Category_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item_descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item_imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item_nameArField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item_nameEnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Category_id {
            get {
                return this.Category_idField;
            }
            set {
                if ((this.Category_idField.Equals(value) != true)) {
                    this.Category_idField = value;
                    this.RaisePropertyChanged("Category_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item_description {
            get {
                return this.Item_descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_descriptionField, value) != true)) {
                    this.Item_descriptionField = value;
                    this.RaisePropertyChanged("Item_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item_image {
            get {
                return this.Item_imageField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_imageField, value) != true)) {
                    this.Item_imageField = value;
                    this.RaisePropertyChanged("Item_image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item_nameAr {
            get {
                return this.Item_nameArField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_nameArField, value) != true)) {
                    this.Item_nameArField = value;
                    this.RaisePropertyChanged("Item_nameAr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item_nameEn {
            get {
                return this.Item_nameEnField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_nameEnField, value) != true)) {
                    this.Item_nameEnField = value;
                    this.RaisePropertyChanged("Item_nameEn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Prices", Namespace="http://schemas.datacontract.org/2004/07/ItemsWCF")]
    [System.SerializableAttribute()]
    public partial class Prices : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Item_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Item_priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item_sizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Item_id {
            get {
                return this.Item_idField;
            }
            set {
                if ((this.Item_idField.Equals(value) != true)) {
                    this.Item_idField = value;
                    this.RaisePropertyChanged("Item_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Item_price {
            get {
                return this.Item_priceField;
            }
            set {
                if ((this.Item_priceField.Equals(value) != true)) {
                    this.Item_priceField = value;
                    this.RaisePropertyChanged("Item_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item_size {
            get {
                return this.Item_sizeField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_sizeField, value) != true)) {
                    this.Item_sizeField = value;
                    this.RaisePropertyChanged("Item_size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/ItemsWCF")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string category_imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string category_nameArField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string category_nameEnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category_image {
            get {
                return this.category_imageField;
            }
            set {
                if ((object.ReferenceEquals(this.category_imageField, value) != true)) {
                    this.category_imageField = value;
                    this.RaisePropertyChanged("category_image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category_nameAr {
            get {
                return this.category_nameArField;
            }
            set {
                if ((object.ReferenceEquals(this.category_nameArField, value) != true)) {
                    this.category_nameArField = value;
                    this.RaisePropertyChanged("category_nameAr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category_nameEn {
            get {
                return this.category_nameEnField;
            }
            set {
                if ((object.ReferenceEquals(this.category_nameEnField, value) != true)) {
                    this.category_nameEnField = value;
                    this.RaisePropertyChanged("category_nameEn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/ItemsWCF")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> category_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string item_descrptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string item_imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string item_nameArField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string item_nameEnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> category_id {
            get {
                return this.category_idField;
            }
            set {
                if ((this.category_idField.Equals(value) != true)) {
                    this.category_idField = value;
                    this.RaisePropertyChanged("category_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string item_descrption {
            get {
                return this.item_descrptionField;
            }
            set {
                if ((object.ReferenceEquals(this.item_descrptionField, value) != true)) {
                    this.item_descrptionField = value;
                    this.RaisePropertyChanged("item_descrption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string item_image {
            get {
                return this.item_imageField;
            }
            set {
                if ((object.ReferenceEquals(this.item_imageField, value) != true)) {
                    this.item_imageField = value;
                    this.RaisePropertyChanged("item_image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string item_nameAr {
            get {
                return this.item_nameArField;
            }
            set {
                if ((object.ReferenceEquals(this.item_nameArField, value) != true)) {
                    this.item_nameArField = value;
                    this.RaisePropertyChanged("item_nameAr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string item_nameEn {
            get {
                return this.item_nameEnField;
            }
            set {
                if ((object.ReferenceEquals(this.item_nameEnField, value) != true)) {
                    this.item_nameEnField = value;
                    this.RaisePropertyChanged("item_nameEn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ItemsWeb.ServiceReference1.CompositeType GetDataUsingDataContract(ItemsWeb.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ItemsWeb.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ItemsWeb.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCategories", ReplyAction="http://tempuri.org/IService1/InsertCategoriesResponse")]
        string InsertCategories(ItemsWeb.ServiceReference1.Categories catinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCategories", ReplyAction="http://tempuri.org/IService1/InsertCategoriesResponse")]
        System.Threading.Tasks.Task<string> InsertCategoriesAsync(ItemsWeb.ServiceReference1.Categories catinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCategories", ReplyAction="http://tempuri.org/IService1/DeleteCategoriesResponse")]
        string DeleteCategories(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCategories", ReplyAction="http://tempuri.org/IService1/DeleteCategoriesResponse")]
        System.Threading.Tasks.Task<string> DeleteCategoriesAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertItems", ReplyAction="http://tempuri.org/IService1/InsertItemsResponse")]
        string InsertItems(ItemsWeb.ServiceReference1.Items iteminfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertItems", ReplyAction="http://tempuri.org/IService1/InsertItemsResponse")]
        System.Threading.Tasks.Task<string> InsertItemsAsync(ItemsWeb.ServiceReference1.Items iteminfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertPrices", ReplyAction="http://tempuri.org/IService1/InsertPricesResponse")]
        string InsertPrices(ItemsWeb.ServiceReference1.Prices priceinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertPrices", ReplyAction="http://tempuri.org/IService1/InsertPricesResponse")]
        System.Threading.Tasks.Task<string> InsertPricesAsync(ItemsWeb.ServiceReference1.Prices priceinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllCategories", ReplyAction="http://tempuri.org/IService1/GetAllCategoriesResponse")]
        ItemsWeb.ServiceReference1.Category[] GetAllCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllCategories", ReplyAction="http://tempuri.org/IService1/GetAllCategoriesResponse")]
        System.Threading.Tasks.Task<ItemsWeb.ServiceReference1.Category[]> GetAllCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllItems", ReplyAction="http://tempuri.org/IService1/GetAllItemsResponse")]
        ItemsWeb.ServiceReference1.Item[] GetAllItems(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllItems", ReplyAction="http://tempuri.org/IService1/GetAllItemsResponse")]
        System.Threading.Tasks.Task<ItemsWeb.ServiceReference1.Item[]> GetAllItemsAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ItemsWeb.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ItemsWeb.ServiceReference1.IService1>, ItemsWeb.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ItemsWeb.ServiceReference1.CompositeType GetDataUsingDataContract(ItemsWeb.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ItemsWeb.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ItemsWeb.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string InsertCategories(ItemsWeb.ServiceReference1.Categories catinfo) {
            return base.Channel.InsertCategories(catinfo);
        }
        
        public System.Threading.Tasks.Task<string> InsertCategoriesAsync(ItemsWeb.ServiceReference1.Categories catinfo) {
            return base.Channel.InsertCategoriesAsync(catinfo);
        }
        
        public string DeleteCategories(int id) {
            return base.Channel.DeleteCategories(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteCategoriesAsync(int id) {
            return base.Channel.DeleteCategoriesAsync(id);
        }
        
        public string InsertItems(ItemsWeb.ServiceReference1.Items iteminfo) {
            return base.Channel.InsertItems(iteminfo);
        }
        
        public System.Threading.Tasks.Task<string> InsertItemsAsync(ItemsWeb.ServiceReference1.Items iteminfo) {
            return base.Channel.InsertItemsAsync(iteminfo);
        }
        
        public string InsertPrices(ItemsWeb.ServiceReference1.Prices priceinfo) {
            return base.Channel.InsertPrices(priceinfo);
        }
        
        public System.Threading.Tasks.Task<string> InsertPricesAsync(ItemsWeb.ServiceReference1.Prices priceinfo) {
            return base.Channel.InsertPricesAsync(priceinfo);
        }
        
        public ItemsWeb.ServiceReference1.Category[] GetAllCategories() {
            return base.Channel.GetAllCategories();
        }
        
        public System.Threading.Tasks.Task<ItemsWeb.ServiceReference1.Category[]> GetAllCategoriesAsync() {
            return base.Channel.GetAllCategoriesAsync();
        }
        
        public ItemsWeb.ServiceReference1.Item[] GetAllItems(string id) {
            return base.Channel.GetAllItems(id);
        }
        
        public System.Threading.Tasks.Task<ItemsWeb.ServiceReference1.Item[]> GetAllItemsAsync(string id) {
            return base.Channel.GetAllItemsAsync(id);
        }
    }
}
