#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemsWCF
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ItemsDB")]
	public partial class ItemsDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCategory(Category instance);
    partial void UpdateCategory(Category instance);
    partial void DeleteCategory(Category instance);
    partial void InsertItem(Item instance);
    partial void UpdateItem(Item instance);
    partial void DeleteItem(Item instance);
    #endregion
		
		public ItemsDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ItemsDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ItemsDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ItemsDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ItemsDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ItemsDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Category> Categories
		{
			get
			{
				return this.GetTable<Category>();
			}
		}
		
		public System.Data.Linq.Table<CatsAr> CatsArs
		{
			get
			{
				return this.GetTable<CatsAr>();
			}
		}
		
		public System.Data.Linq.Table<CatsEn> CatsEns
		{
			get
			{
				return this.GetTable<CatsEn>();
			}
		}
		
		public System.Data.Linq.Table<Item> Items
		{
			get
			{
				return this.GetTable<Item>();
			}
		}
		
		public System.Data.Linq.Table<CatItemsAr> CatItemsArs
		{
			get
			{
				return this.GetTable<CatItemsAr>();
			}
		}
		
		public System.Data.Linq.Table<CatItemsEn> CatItemsEns
		{
			get
			{
				return this.GetTable<CatItemsEn>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categories")]
	public partial class Category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _category_nameAr;
		
		private string _category_nameEn;
		
		private string _category_image;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Oncategory_nameArChanging(string value);
    partial void Oncategory_nameArChanged();
    partial void Oncategory_nameEnChanging(string value);
    partial void Oncategory_nameEnChanged();
    partial void Oncategory_imageChanging(string value);
    partial void Oncategory_imageChanged();
    #endregion
		
		public Category()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_nameAr", DbType="NVarChar(50)")]
		public string category_nameAr
		{
			get
			{
				return this._category_nameAr;
			}
			set
			{
				if ((this._category_nameAr != value))
				{
					this.Oncategory_nameArChanging(value);
					this.SendPropertyChanging();
					this._category_nameAr = value;
					this.SendPropertyChanged("category_nameAr");
					this.Oncategory_nameArChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_nameEn", DbType="NVarChar(50)")]
		public string category_nameEn
		{
			get
			{
				return this._category_nameEn;
			}
			set
			{
				if ((this._category_nameEn != value))
				{
					this.Oncategory_nameEnChanging(value);
					this.SendPropertyChanging();
					this._category_nameEn = value;
					this.SendPropertyChanged("category_nameEn");
					this.Oncategory_nameEnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_image", DbType="NVarChar(MAX)")]
		public string category_image
		{
			get
			{
				return this._category_image;
			}
			set
			{
				if ((this._category_image != value))
				{
					this.Oncategory_imageChanging(value);
					this.SendPropertyChanging();
					this._category_image = value;
					this.SendPropertyChanged("category_image");
					this.Oncategory_imageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CatsAr")]
	public partial class CatsAr
	{
		
		private int _id;
		
		private string _category_nameAr;
		
		private string _category_image;
		
		public CatsAr()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_nameAr", DbType="NVarChar(50)")]
		public string category_nameAr
		{
			get
			{
				return this._category_nameAr;
			}
			set
			{
				if ((this._category_nameAr != value))
				{
					this._category_nameAr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_image", DbType="NVarChar(MAX)")]
		public string category_image
		{
			get
			{
				return this._category_image;
			}
			set
			{
				if ((this._category_image != value))
				{
					this._category_image = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CatsEn")]
	public partial class CatsEn
	{
		
		private int _id;
		
		private string _category_nameEn;
		
		private string _category_image;
		
		public CatsEn()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_nameEn", DbType="NVarChar(50)")]
		public string category_nameEn
		{
			get
			{
				return this._category_nameEn;
			}
			set
			{
				if ((this._category_nameEn != value))
				{
					this._category_nameEn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_image", DbType="NVarChar(MAX)")]
		public string category_image
		{
			get
			{
				return this._category_image;
			}
			set
			{
				if ((this._category_image != value))
				{
					this._category_image = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Items")]
	public partial class Item : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _item_nameAr;
		
		private string _item_nameEn;
		
		private string _item_descrptionAr;
		
		private string _item_descrptionEn;
		
		private string _item_size;
		
		private System.Nullable<decimal> _item_price;
		
		private string _item_size2;
		
		private System.Nullable<decimal> _item_price2;
		
		private string _item_image;
		
		private System.Nullable<int> _category_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onitem_nameArChanging(string value);
    partial void Onitem_nameArChanged();
    partial void Onitem_nameEnChanging(string value);
    partial void Onitem_nameEnChanged();
    partial void Onitem_descrptionArChanging(string value);
    partial void Onitem_descrptionArChanged();
    partial void Onitem_descrptionEnChanging(string value);
    partial void Onitem_descrptionEnChanged();
    partial void Onitem_sizeChanging(string value);
    partial void Onitem_sizeChanged();
    partial void Onitem_priceChanging(System.Nullable<decimal> value);
    partial void Onitem_priceChanged();
    partial void Onitem_size2Changing(string value);
    partial void Onitem_size2Changed();
    partial void Onitem_price2Changing(System.Nullable<decimal> value);
    partial void Onitem_price2Changed();
    partial void Onitem_imageChanging(string value);
    partial void Onitem_imageChanged();
    partial void Oncategory_idChanging(System.Nullable<int> value);
    partial void Oncategory_idChanged();
    #endregion
		
		public Item()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_nameAr", DbType="NVarChar(50)")]
		public string item_nameAr
		{
			get
			{
				return this._item_nameAr;
			}
			set
			{
				if ((this._item_nameAr != value))
				{
					this.Onitem_nameArChanging(value);
					this.SendPropertyChanging();
					this._item_nameAr = value;
					this.SendPropertyChanged("item_nameAr");
					this.Onitem_nameArChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_nameEn", DbType="NVarChar(50)")]
		public string item_nameEn
		{
			get
			{
				return this._item_nameEn;
			}
			set
			{
				if ((this._item_nameEn != value))
				{
					this.Onitem_nameEnChanging(value);
					this.SendPropertyChanging();
					this._item_nameEn = value;
					this.SendPropertyChanged("item_nameEn");
					this.Onitem_nameEnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_descrptionAr", DbType="NVarChar(MAX)")]
		public string item_descrptionAr
		{
			get
			{
				return this._item_descrptionAr;
			}
			set
			{
				if ((this._item_descrptionAr != value))
				{
					this.Onitem_descrptionArChanging(value);
					this.SendPropertyChanging();
					this._item_descrptionAr = value;
					this.SendPropertyChanged("item_descrptionAr");
					this.Onitem_descrptionArChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_descrptionEn", DbType="NVarChar(MAX)")]
		public string item_descrptionEn
		{
			get
			{
				return this._item_descrptionEn;
			}
			set
			{
				if ((this._item_descrptionEn != value))
				{
					this.Onitem_descrptionEnChanging(value);
					this.SendPropertyChanging();
					this._item_descrptionEn = value;
					this.SendPropertyChanged("item_descrptionEn");
					this.Onitem_descrptionEnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_size", DbType="NVarChar(50)")]
		public string item_size
		{
			get
			{
				return this._item_size;
			}
			set
			{
				if ((this._item_size != value))
				{
					this.Onitem_sizeChanging(value);
					this.SendPropertyChanging();
					this._item_size = value;
					this.SendPropertyChanged("item_size");
					this.Onitem_sizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_price", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> item_price
		{
			get
			{
				return this._item_price;
			}
			set
			{
				if ((this._item_price != value))
				{
					this.Onitem_priceChanging(value);
					this.SendPropertyChanging();
					this._item_price = value;
					this.SendPropertyChanged("item_price");
					this.Onitem_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_size2", DbType="NVarChar(50)")]
		public string item_size2
		{
			get
			{
				return this._item_size2;
			}
			set
			{
				if ((this._item_size2 != value))
				{
					this.Onitem_size2Changing(value);
					this.SendPropertyChanging();
					this._item_size2 = value;
					this.SendPropertyChanged("item_size2");
					this.Onitem_size2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_price2", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> item_price2
		{
			get
			{
				return this._item_price2;
			}
			set
			{
				if ((this._item_price2 != value))
				{
					this.Onitem_price2Changing(value);
					this.SendPropertyChanging();
					this._item_price2 = value;
					this.SendPropertyChanged("item_price2");
					this.Onitem_price2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_image", DbType="NVarChar(MAX)")]
		public string item_image
		{
			get
			{
				return this._item_image;
			}
			set
			{
				if ((this._item_image != value))
				{
					this.Onitem_imageChanging(value);
					this.SendPropertyChanging();
					this._item_image = value;
					this.SendPropertyChanged("item_image");
					this.Onitem_imageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", DbType="Int")]
		public System.Nullable<int> category_id
		{
			get
			{
				return this._category_id;
			}
			set
			{
				if ((this._category_id != value))
				{
					this.Oncategory_idChanging(value);
					this.SendPropertyChanging();
					this._category_id = value;
					this.SendPropertyChanged("category_id");
					this.Oncategory_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CatItemsAr")]
	public partial class CatItemsAr
	{
		
		private System.Nullable<int> _category_id;
		
		private string _item_nameAr;
		
		private string _item_descrptionAr;
		
		private string _Item_size;
		
		private System.Nullable<decimal> _Item_price;
		
		private string _Item_size2;
		
		private System.Nullable<decimal> _Item_price2;
		
		private string _category_image;
		
		private string _item_image;
		
		public CatItemsAr()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", DbType="Int")]
		public System.Nullable<int> category_id
		{
			get
			{
				return this._category_id;
			}
			set
			{
				if ((this._category_id != value))
				{
					this._category_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_nameAr", DbType="NVarChar(50)")]
		public string item_nameAr
		{
			get
			{
				return this._item_nameAr;
			}
			set
			{
				if ((this._item_nameAr != value))
				{
					this._item_nameAr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_descrptionAr", DbType="NVarChar(MAX)")]
		public string item_descrptionAr
		{
			get
			{
				return this._item_descrptionAr;
			}
			set
			{
				if ((this._item_descrptionAr != value))
				{
					this._item_descrptionAr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_size", DbType="NVarChar(50)")]
		public string Item_size
		{
			get
			{
				return this._Item_size;
			}
			set
			{
				if ((this._Item_size != value))
				{
					this._Item_size = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_price", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Item_price
		{
			get
			{
				return this._Item_price;
			}
			set
			{
				if ((this._Item_price != value))
				{
					this._Item_price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_size2", DbType="NVarChar(50)")]
		public string Item_size2
		{
			get
			{
				return this._Item_size2;
			}
			set
			{
				if ((this._Item_size2 != value))
				{
					this._Item_size2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_price2", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Item_price2
		{
			get
			{
				return this._Item_price2;
			}
			set
			{
				if ((this._Item_price2 != value))
				{
					this._Item_price2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_image", DbType="NVarChar(MAX)")]
		public string category_image
		{
			get
			{
				return this._category_image;
			}
			set
			{
				if ((this._category_image != value))
				{
					this._category_image = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_image", DbType="NVarChar(MAX)")]
		public string item_image
		{
			get
			{
				return this._item_image;
			}
			set
			{
				if ((this._item_image != value))
				{
					this._item_image = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CatItemsEn")]
	public partial class CatItemsEn
	{
		
		private System.Nullable<int> _category_id;
		
		private string _item_nameEn;
		
		private string _item_descrptionEn;
		
		private string _Item_size;
		
		private System.Nullable<decimal> _Item_price;
		
		private string _Item_size2;
		
		private System.Nullable<decimal> _Item_price2;
		
		private string _category_image;
		
		private string _item_image;
		
		public CatItemsEn()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", DbType="Int")]
		public System.Nullable<int> category_id
		{
			get
			{
				return this._category_id;
			}
			set
			{
				if ((this._category_id != value))
				{
					this._category_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_nameEn", DbType="NVarChar(50)")]
		public string item_nameEn
		{
			get
			{
				return this._item_nameEn;
			}
			set
			{
				if ((this._item_nameEn != value))
				{
					this._item_nameEn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_descrptionEn", DbType="NVarChar(MAX)")]
		public string item_descrptionEn
		{
			get
			{
				return this._item_descrptionEn;
			}
			set
			{
				if ((this._item_descrptionEn != value))
				{
					this._item_descrptionEn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_size", DbType="NVarChar(50)")]
		public string Item_size
		{
			get
			{
				return this._Item_size;
			}
			set
			{
				if ((this._Item_size != value))
				{
					this._Item_size = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_price", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Item_price
		{
			get
			{
				return this._Item_price;
			}
			set
			{
				if ((this._Item_price != value))
				{
					this._Item_price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_size2", DbType="NVarChar(50)")]
		public string Item_size2
		{
			get
			{
				return this._Item_size2;
			}
			set
			{
				if ((this._Item_size2 != value))
				{
					this._Item_size2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_price2", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Item_price2
		{
			get
			{
				return this._Item_price2;
			}
			set
			{
				if ((this._Item_price2 != value))
				{
					this._Item_price2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_image", DbType="NVarChar(MAX)")]
		public string category_image
		{
			get
			{
				return this._category_image;
			}
			set
			{
				if ((this._category_image != value))
				{
					this._category_image = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_image", DbType="NVarChar(MAX)")]
		public string item_image
		{
			get
			{
				return this._item_image;
			}
			set
			{
				if ((this._item_image != value))
				{
					this._item_image = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
